include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
    strict-inference: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    unused_import: error
    dead_code: error
    unnecessary_cast: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_aware_operator_on_extension_on_nullable: error
    unnecessary_null_checks: error
    unnecessary_lambdas: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    avoid_return_types_on_setters: true
    avoid_init_to_null: true
    avoid_print: true
    unnecessary_this: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    require_trailing_commas: true